DROP DATABASE IF EXISTS burgs_db;
CREATE DATABASE burgs_db;
USE burgs_db;

CREATE TABLE burgs (
id INT  AUTO_INCREMENT
, name VARCHAR(255) NOT NULL
, devour BOOLEAN DEFAULT false
, PRIMARY KEY (id)
);


